[pytest]
testpaths = test_get_pheno.py
filterwarnings =
    ignore:.*np\.typeDict.*:DeprecationWarning:tables.*
    ignore:.*np\.object.*:DeprecationWarning:tables.*
    ignore:distutils Version classes are deprecated.*:DeprecationWarning:tables.*
